### ISSUE TITLE
Lists and tuples populated with numpy objects

### ISSUE THREAD

**Issue by fleming79** [telegraphic/hickle#12]
Please consider adding this capability similar to nested dictionaries.

**Comment by telegraphic** [comment]
Arg, I was hoping to add this in my latest updates, but it's a bit more subtle than I'd hoped. Hopefully I'll get this in the next update, I haven't forgotten!

**Comment by telegraphic** [comment]
Ok, this should now be supported. Can you give it a try and I'll close the issue if it's doing what you expect? If you manage to make it crash please give me some code snippets so I can make a unit test up.

In order to do this, we have to check if the list contains any numpy arrays, which might turn out to slow down the code in certain circumstances. There would also be circumstances where weird stuff could happen, e.g. a really long list of integers with a numpy.ndarray tacked on the end. I'm not sure how to tackle things like that, but for now I think the functionality is as-expected for **non-bizarre data**.
