### ISSUE TITLE
Problems with handling kwargs

### ISSUE THREAD

**Issue by texadactyl** [telegraphic/hickle#157]
Running on my own laptop with these versions:
* h5py 3.6.0
* hdf5plugin 3.2.0
* hdf5-tools (C/C++ library) 1.10.7 

I installed https://github.com/telegraphic/hickle

Source code:
[hackle.py.txt](https://github.com/telegraphic/hickle/files/7864595/hackle.py.txt)

The source code executes without the appearance of error messages.  However, an ```h5dump``` execution shows that the specified compression parameters are not getting passed through to ```h5py```:
[hackle_h5.txt](https://github.com/telegraphic/hickle/files/7864657/hackle_h5.txt)

Imbedded in the hackle_h5.txt attachment, one can see that there are 3 occurrences of h5dump error messages (stderr):
```h5dump error: unable to print data```

**Comment by texadactyl** [comment]
Opinions:
* The problem is in function ```_dump``` and the call from ```dump```, source file ```hickle.py```.
* I can see after debugging a bit that the kwargs appear okay but the call to "create_dataset" is strange.  Normally, there should be an open HDF5 object that this member function is preceded by E.g. "h5file.create_dataset" as found in blimpy.
* Please do not take this the wrong way but a pickle replacement should be less convoluted to read.

**Comment by hernot** [comment]
I guess you example is not quite accurate for testing. 
``
array_obj = np.array((2, 3), dtype="float32")
`` 
I guess your 2 by 3 32 bit float array is just good enough to chase a ghost. In order to understand why your array is not compressed one has to know how compression works in general and how libhdff5 deals with data which is too small to be reasonably be compressed. Means data for which. after adding the non avoidable headers, compression tables and other necessary housekeeping bytes, the compressed stream would require more space than the non compressed raw data stream.
In that case libhdf5 stores the raw data as needing less space and skips compression completely. And this might here be the ghost you are chasing. So i do suggest repeat the test with the following array to be sure we can here exclude the skipped compression ghost.

``
array_obj = np.random.rand([200,300], dtype="float32")
`` 

 Now you should see that the data is compressed using BitShuffle filter. 

Also see the note in the [custom compression filters](https://docs.h5py.org/en/3.1.0/high/dataset.html?highlight=filter#filter-pipeline) section of the  h5py manual which states:
``` 
The underlying implementation of the compression filter will have the H5Z_FLAG_OPTIONAL flag set. This indicates that if the compression filter doesn’t compress a block while writing, no error will be thrown. The filter will then be skipped when subsequently reading the block.
```
And as stated above i do think the most likely reason for not seeing any compression is that your 2 element array is to short gaining anything from compression and thus libhdf5 simply skips your filter.

And the h5dump error messages just tell that h5dump is not able to convert the data to and thus print in human readable form.
```
unable to print data 
```
But it does not tell anything about whether the file is corrupt or not. Why it can not print the content of the array itself i would have to guess. In the other two cases it seems as if it is not able to print data reference objects when they occur as attribute value instead as hardlink to dataset or group.  I have never used h5dump but had similar issues and hassles using hdf5Compass. I finally decided to risk the passage through the installatoin hell and install a recent version of the official hdfview tool. The most tricky part for me was to figure that the centos package is also meant for beeing installed on linux.

**Comment by hernot** [comment]
> 
>     * Please do not take this the wrong way but a pickle replacement should be less convoluted to read.

Hickle is not just yet another pickle replacement, it also has to bridge the opposit aims and goals of pickle  and hdf5. Pickle is designed to most efficiently and with least efforts serialize the content of the memory, the python object and data structure as represented in memory. HDF5 is designed to store a few hug data matrices along with necessary houskeeping and administartive data and allow to search for and extract individual datasets. Storing plenty of small arrays and scalar values will result in bloated hdf5 files. For example our datasets which use in pickle format up to 500 MB when naively storing them in hdf5 without as appearing in memory result in hdf5 files of  at least 5 GB in most cases event up to 20 GB. For details see all the fruitful, long and thorough discussions and @1313e and I had on the issues #125 and #145 and the pullrequests #138 and #149. Especially also see my rather late accepting of the fact that hdf5 has an opposing purpose to pickle at the end of issue #131 [https://github.com/telegraphic/hickle/issues/125#issuecomment-732203914](https://github.com/telegraphic/hickle/issues/125#issuecomment-732203914)

An the things you call convoluted is necessary to properly map between the world of pickle and the world of hdf5. Its not just as simple dumping of memory to yet another file format. It needs a clever translation from memory layout and objects structures which can be huge and split into tiny details consisting of tons of individual scalar values to a format which is designed to store few additional information along with huge tables of data and large sets of images, either by simply naming their file name or by embedding as individual data chunks. Therefore @telegraphic and @1313e  have decided to separate the core machinery of hickle from the actual knowledge on  how to translate a python list or dictionary a custom object or a string in something which is storable as efficient as possible in an hdf5 file. The current well thought design allows to add custom loaders for ones data objects without touching the hickle code it allows to extend the set of bundled loaders without changing neither the interface of hickle nor the file structure used to store the data. 


Ant yes in the beginning it might be helpful for contributors if there would exist a short document, readme  describing the basic structure and patterns used in hickle to make this translation happen in the most general and transparent manner and thereby at the same time avoiding to lock in users of hickle to what @telegraphic @1313e me and others contributors could imaging so far that could be useful as we everyday experience when using commercial products.  I try to give you an overview thereby answering your second question. @telegraphic and/or @1313e may i ask you to review and correct any bits i miss or get wrong.  

>     * I can see after debugging a bit that the kwargs appear okay but the call to "create_dataset" is strange.  Normally, there should be an open HDF5 object that this member function is preceded by E.g. "h5file.create_dataset" as found in blimpy.  Was this somehow set up by the call to `loader.load_loader`?

`hickle.dump` and `hickle.load` can be called in one of the following ways (see also issue #144)
```
some_data = {'data1':[1,2,3,4],'data2':'some string','data3':np.ones([12,200],dtype=np.uint16)}
hickle.dump(some_data,"store_some_data_on_a_named_file.hkl","w",...)

with open("store_some_data_on_file_or_file_like_object.myfile",'wb') as my_file:
    hickle.dump(some_data,my_file,"wb")

import io

store_in_memory = io.BytesIO()
hickle.dump(some_data,store_in_meory,"wb")

embed_in_my_hdf5_file = h5py.File.open("my_fancy_hdf5_file.hdf","w")
hickle.dump(some_data,embed_in_my_hdf5_file,"wb",root="/additional/info/hickle/dump")

sub_tree_to_dump_to = embed_in_my_hdf5_file['/better/dump/to/here']
hickle.dump(some_data,sub_tree_to_dump_to,"wb")

```

in all these cases the `hickle.fileio.file_opener` method called on line 122 for `hickle.dump` function and on line 321 for `hickle.load` ensures that the underlying hdf5 file is opened and the appropriate group to dump to, in most cases this is root `/` is passed on to `hickle._dump` and `hickle._load` functions in lines 236, 374 and 379 as `h_group` or` h_node` parameter respective.

the hickle.lookup.LoaderManager.load_loader method called on lines 122 selects the appropriate create_dataset function to be used to translate the memory structure of the py_obj into a suitable hdf5 file representation.

```
 122     py_obj_type, (create_dataset, base_type,memoise) = loader.load_loader(py_obj.__class__)
``` 
It is implemented along the load on demand principle and pattern. Only those functions, methods and classes are imported and thus loaded (in simplest case from `hickle/loaders/load_*.py` modules which are required to store the content of `some_data` in the above examples. Therefore it is also called by `hickle._load` on line 436 to ensure that the load_dataset or PyContainer object necessary to properly restore the data re present before restoring is attempted.

```
436     py_obj_type,(_,_,memoise) = loader.load_loader(py_obj_type,base_type=base_type)
```

As already sayed the actual `h5py.Dataset` or `h5py.Group` objects are created by the individual `create_dataset` function on the `h_group` object by calling `h5py.Group.create_dataset` and `h5py.Group.create_group` methods. Thereby it has to be ensured that `compression` and `compression_opts` keyword arguments are only passed to `h5py.Group.create_dataset` for data which is considered compressible by libhdf5 and thus h5py. Plain python strings, bytes and scalars aren't. This is why hickle provides the "named dict comprehension" `hickle.helpers.no_compression` to ensure any keyword arguments which would cause libhdf5 and thus h5py throw an exception. Which other keywords have to be filtered you find in the definition of `hickle.helpers.no_compression`.

When done the `create_dataset` function has to return the newly created `h5py.Dataset` or `h5py.Group` object to allow hickle to attach a reference to the `py_object_type` of the py_obj just at least partially dumped. On `h5py.Group` objects the `h_subitems` list returned on line 129 along with the new `h_node` object contain a tuple or list providing the *name*,  the actual sub item  additional attributes to store along with if any, and the keyword arguments as passed to `create_dataset` function. Even though not yet used the latter would allow the `create_dataset` function to add additional kwargs to `h5py.Group.create_dataset` to be used in creating the structure for the sub item or remove some. 

On load the `load_fcn` and the `PyContainter` object take care that all data is properly restored again including any references to objects shared between multiple objects. Whether shared objects should be stored anew on every occurrence of its reference or a hardlink should be created to relfect its shared nature can be defined by the loader through the memoise flag which is provided by `hickle.lookup.LoaderManager.load_loaders` method to `hickle._dump` method.

Yes it in the start seems to be quite convoluted how hickle works but the alternative would be to intermix data type dependent knowledge with general approach to build the file structure. And yes the whole could also be implemented iteratively instead of using recursion, which would possibly provide some additional speed-up. @telegraphic, @1313e  could you please provide some insight into what has lead to your decision to base hickle inner mechanics on recursion instead of implementing everything iteratively. At that time I didn't even yet know that hickle exists nor that it would spare me a lot of hassle storing and sharing my data between different environments using distinct and quite diverse programming languages nor that my contribution to it would be welcomed nor how deep i would be involved in. Therefore i fell being the wrong person to say anything about it or even comment or question it,

**Comment by 1313e** [comment]
I think you nailed the explanation pretty much.
I however wasn't on the project yet when the decision on storing recursively was made, but I think the reason for it was simply because it is the easiest way of dealing with nested containers.
There is no way to tell how many nested levels a container has from the front without doing lots of checks.
It is much easier to just go through them recursively layer-by-layer, and storing them that way.

**Comment by texadactyl** [comment]
The file is a valid test case.  However, I did not use the right options with ```h5dump``` or I would have seen the filter action in the dataset.
```
HDF5 "xx.hkl" {
GROUP "/" {
   ATTRIBUTE "HICKLE_PYTHON_VERSION" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   ATTRIBUTE "HICKLE_VERSION" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_UTF8;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
   }
   DATASET "data" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      STORAGE_LAYOUT {
         CHUNKED ( 2 )
         SIZE 20 (0.400:1 COMPRESSION)
      }
      FILTERS {
         USER_DEFINED_FILTER {
            FILTER_ID 32008
            COMMENT bitshuffle; see https://github.com/kiyo-masui/bitshuffle
            PARAMS { 0 3 4 0 2 }
         }
      }
      FILLVALUE {
         FILL_TIME H5D_FILL_TIME_ALLOC
         VALUE  H5D_FILL_VALUE_DEFAULT
      }
      ALLOCATION_TIME {
         H5D_ALLOC_TIME_INCR
      }
      ATTRIBUTE "np_dtype" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
      }
      ATTRIBUTE "type" {
         DATATYPE  H5T_REFERENCE { H5T_STD_REF_OBJECT }
         DATASPACE  SCALAR
      }
   }
   GROUP "hickle_types_table" {
      DATASET "0" {
         DATATYPE  H5T_STRING {
            STRSIZE 1;
            STRPAD H5T_STR_NULLPAD;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 1, 32 ) / ( 1, 32 ) }
         STORAGE_LAYOUT {
            CHUNKED ( 1, 32 )
            SIZE 50 (0.640:1 COMPRESSION)
         }
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32008
               COMMENT bitshuffle; see https://github.com/kiyo-masui/bitshuffle
               PARAMS { 0 3 1 0 2 }
            }
         }
         FILLVALUE {
            FILL_TIME H5D_FILL_TIME_ALLOC
            VALUE  H5D_FILL_VALUE_DEFAULT
         }
         ALLOCATION_TIME {
            H5D_ALLOC_TIME_INCR
         }
         ATTRIBUTE "base_type" {
            DATATYPE  H5T_REFERENCE { H5T_STD_REF_OBJECT }
            DATASPACE  SCALAR
         }
      }
      DATASET "ndarray" {
         DATATYPE  H5T_STRING {
            STRSIZE 1;
            STRPAD H5T_STR_NULLPAD;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  NULL
         STORAGE_LAYOUT {
            CONTIGUOUS
            SIZE 0
            OFFSET 18446744073709551615
         }
         FILTERS {
            NONE
         }
         FILLVALUE {
            FILL_TIME H5D_FILL_TIME_IFSET
            VALUE  H5D_FILL_VALUE_DEFAULT
         }
         ALLOCATION_TIME {
            H5D_ALLOC_TIME_LATE
         }
      }
   }
}
}

```

I am closing this issue.

**Comment by hernot** [comment]
I do not know h5dump i do not use it so i can not say anything about it. Nevertheless there can not be any such option which would make the filter action visible given your 32bit float long numpy array representing an 8 bytes worth payload . As I have explained to in my above comment it is very likely that lib hdf5 has silently skipped the filter and stored the raw data instead. 

As libhdf5 applies compressoin on dataset and not on file level this behaviour is independent of compression filter selected and thus would have happened for for example in case of plain gzip compression filter too. For the latter, if i remember correctly, the minimum header size is least 1024 non avoidable bytes extra added to your 8 byte long array. So when compressed it would require 1032  bytes to be stored in the resulting hdf5 file instead of 8 bytes for just storing the array. As indicated by the cited excerpts  of the h5py and the libhdf5 manuals libhdf5 drops the compressed stream and stores your data uncompressed. So the only possibility to verify that the filter is applied and that there are no other issues is to increase the size of the array so that its raw representation covers significantly more bytes than the bytes prepended and interpended and appended by the compression filter for housekeeping, header and code-tables.

**Comment by texadactyl** [comment]
As I explained above, `h5dump` did NOT skip the compression filter.

**Comment by hernot** [comment]
Also on the risk that I miss read you already since a several posts and also for documenting a bit my findings about hdf5 files for others which might have initial difficulties to match the pickle and the hdf5 file world bridged by hickle like i for example had when starting to contribute to hickle.

I did never say that h5dump did skip the filter. I explained that libhdf5 has skipped it already when it stored your two element array which caused the impression on your side that hickle would have lost or silently dropped the parameter setting for the filter. As an analogue  picture view an hdf5 file as virtual file system. The groups as the  directories thereon and the datasets as the files stored therein along with the necessary file and directory attributes and metadata. Based on this picture So you can use your normal filesystem to simulate the reported situation and demonstrate the reason for the compression filter not being applied and skipped instead by libhdf5 doing the work tat the core of h5py.

Just try the following on a regular file system (the below example assume availability of shell/bash like command interpreter and the availability of the gzip program)

```
# the -n is used to suppress trailing '\n' otherwise appended by echo
echo -n  "DT42AD56" > test.txt
echo -n "DT42AD56" | gzip > test.gz
ls -l test*
```

The result will be two files a `test.txt` which is exactly 8 bytes in size comparable to the two element numpy array payload in the examples in preceding posts and a `test.gz` which is  28 bytes in size. 20 bytes more as necessary to store the character sequence `00420056`. And that is exactly the situation where libhdf5 `h5d.create` which is called by `h5py.Group.create_dataset` decides to skip the compression filter eg. ´gzip` and store the bytes directly. 
When the hdf5 file is now viewed the preferred hdf5 inspection tool for example h5dump than it looks like as if the `compression` and `compression_opts` keywords would have never been passed to `h5py.Group.create_dataset` even though they have just been ignored by `h5d.create` method of libhdf5 due to the too small size of the 8 byte payload to gain any benefit from compression.
