### ISSUE TITLE
Hickling doesn't preserve list order

### ISSUE THREAD

**Issue by craffel** [telegraphic/hickle#26]
Is this the expected behavior?  Seems to be true in general, this isn't a contrived example.

```Python
d = [np.arange(n) for n in range(20)]
print d[:4]
hickle.dump(d, 'test.h5')
print hickle.load('test.h5')[:4]
```
yields
```
[array([], dtype=int64), array([0]), array([0, 1]), array([0, 1, 2])]
[array([], dtype=int64), array([0]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])]
```

**Comment by telegraphic** [comment]
Hi @craffel 

Ouch, that's a bad one. Definitely a bug, not a feature. 

The mapping of python data structures into HDF has turned out to have some subtleties (as was being discussed in #24), in particular to do with iterables. I'm hoping to release a refactored version of the code soonish, that will better deal with arbitrary python iterables. Maintaining backwards compatibility is a hoop that might take a little bit longer to solve however.

**Comment by craffel** [comment]
Right on, I will stay tuned.

**Comment by telegraphic** [comment]
Ok, the newly refactored code does an explicit sort on group IDs to check that list order is kept the same. The code above passes unit tests in Travis so I'm closing the issue!

**Comment by craffel** [comment]
Nice, thanks!
