### ISSUE TITLE
Storing scalars with compression

### ISSUE THREAD

**Issue by kaythurley** [telegraphic/hickle#37]
When running hickle.dump({'d': 0}, 'dummy.hkl', mode='w', compression='gzip') with hickle 2.0.4 I get a "Scalar datasets don't support chunk/filter options" from h5py. However, the same command works with hickle 1.1.1. What did change?
Also hickle.dump({'d': 0}, 'dummy.hkl', mode='w') works with hickle 2.0.4.

**Comment by telegraphic** [comment]
Hi @kaythurley, I've made a change (currently in the dev branch) that fixes this.

To explain what was going on here: fundamentally, you can't compress a scalar that stands alone -- you need an array of numbers/characters that are in some way 'similar' for any compression algorithm to work. `h5py` was complaining as it doesn't allow a scalar dataset to be created with a compression flag present.

Nevertheless, it is entirely reasonable for a user to have something like:
```
dd = {'d' : 0,
'e': [0,1,2,3,4,5,6,0],
'f': really big numpy array here that we really want to compress
}
```
where item `d` will not be compressible, but `e` and `f` are compressible, and `hickle` shouldn't choke just because we put a scalar in our dictionary too. Now, hickle won't try to compress scalar datasets, and will skip it and continue on its merry way.

**Comment by telegraphic** [comment]
Doing an issue tidy-up right now, closing this as there's now a unit test to check for it.
