### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by thvasilo** [telegraphic/hickle#8]
Are there any plans to make hickle compatible with Python 3?

What kind of issues would an attempted transition face?

**Comment by telegraphic** [comment]
Some notes on issues that will need to be addressed:

* Print statements require ()
* `unicode` type does not exist in Py3. Py2 code requires strings and unicode to be treated separate.
* Similarly, `long` and `int` have been merged in Py3. 

The straightforward fixes will break the unit-tests on Py2 (as str != unicode on Py2), so it's not possible to write generic code that suits both. The solution is (probably) to use the [six](https://pythonhosted.org/six/) module.

Useful reference for later: http://python-future.org/compatible_idioms.html

**Comment by femtotrader** [comment]
Any news about this ?

**Comment by telegraphic** [comment]
In a word: no. 

However, I have been thinking about this though, and one possibility is to add an attribute in the HDF5 file `PYVERSION=2` or `PYVERSION=3`. This would then allow different handling of strings as required for the two python versions.

Not sure when I will have time to look into this further but I'll try this week.

**Comment by fleming79** [comment]
I'd like to second this. Looking forward to seeing  a python 3 version.

**Comment by yggdr** [comment]
Since I'm looking to use HDF5 in a project, I took a swing at py3 compatibility (albeit a hackish one). Nested lists of numbers can be hickled, but strings give me problems. If anyone wants to take a look, it's in my fork's feature/py3 branch.

**Comment by telegraphic** [comment]
Thanks @yggdr, Py 3.5 support definitely needs to happen! The last few months I've a few colleagues have moved to Py 3 and every student I meet is using it, so now is probably the time to invest. I'm going to tag this 'pull-request-welcome', but I'll hopefully set myself up a Py 3 environment soon.

**Comment by mschrimpf** [comment]
Thanks for looking into this @telegraphic. Any thoughts on the timeline? I'd love to use it (in Python3).

**Comment by telegraphic** [comment]
Hi @mschrimpf, I've been snowed under recently, but maybe some time late October?

**Comment by telegraphic** [comment]
Making some progress here finally. This but from the h5py website explains what will be a big irritation:
http://docs.h5py.org/en/latest/strings.html

**Exceptions for Python 3**

Most strings in the HDF5 world are stored in ASCII, which means they map to byte strings. But in Python 3, there’s a strict separation between data and text, which intentionally makes it painful to handle encoded strings directly.

So, when reading or writing scalar string attributes, on Python 3 they will always be returned as type str, regardless of the underlying storage mechanism. The regular rules for writing apply; to get a fixed-width ASCII string, use numpy.string_, and to get a variable-length ASCII string, use bytes.

**What about NumPy’s U type?**
NumPy also has a Unicode type, a UTF-32 fixed-width format (4-byte characters). HDF5 has no support for wide characters. Rather than trying to hack around this and “pretend” to support it, h5py will raise an error when attempting to create datasets or attributes of this type.

**Comment by Ilija995** [comment]
I'm looking forward to Py3 support. Is there any ETA?

**Comment by telegraphic** [comment]
Hi all, preliminary Python 3 support can be found in the [dev branch](https://github.com/telegraphic/hickle/tree/dev)!

It would be excellent if people (i.e. y'all) can try it out, find bugs, and fix them. For now, please consider this 'experimental'. Input from beta testers is needed before the dev branch can become the master!

An issue going forward is that Py2 and Py3 are fundamentally incompatible in terms of unicode and long support. For example, what should happen when you try and load a Py2-created hickled with contents `{u'a' : 'test', 'b' : 1L}` in Py3? 

Another goal is maintaining backwards compatibility as far as possible, or at least failing gracefully. My plan here is to add attributes 'hickle version = 3.0.0' and 'python version = 2.7.9' or something similar to the root group

**Comment by eendebakpt** [comment]
@telegraphic We have been using hickle with python3 for some time now and it works well for us. It would be great if dev could be merged to master (so that pip packages are available directly)

**Comment by engrean** [comment]
Just wondering when this is going to be merged to master and released?

**Comment by telegraphic** [comment]
@engrean Good question. I will aim for end of February. Main outstanding thing is to do something sane if you try and load a Py2 generated file with string/unicode objects into Py3, with string/bytes. I think a warning should be thrown, and then a 'best effort' loading should be attempted.

**Comment by telegraphic** [comment]
Took me a while longer, but Py3 support is now out of dev and merged into master, so closing this issue! 🎈 🎉
